local world = {
	RED_COLOR = vmath.vector4(0.76, 0.27, 0.27, 1),
	YELLOW_COLOR = vmath.vector4(1, 0.85, 0, 1),
	GREY_COLOR = vmath.vector4(0.90, 0.90, 0.90, 1),
	STARTING_ROW = 1,
	STARTING_LEFT_LIMIT = 56,
	STARTING_LENGTH = 3,
	STARTING_SPEED = 0.5,
	STARTING_TIME = 15,
	STARTING_SCORE = 0,
	SPEEDUP_FACTOR = 0.03,
	HERO_START_POS = vmath.vector3(72, 16, 8),
	HERO_SPEED = 8,
	HERO_DELAY = 0.4,
	SKULL_START_POS = vmath.vector3(72, 8, 8),
	SKULL_SPEED = 8,
	SKULL_DELAY = 0.4,
	CHEST_START_POS = vmath.vector3(72, 288, 0),
	PANEL_START_POS = vmath.vector3(24, 24, -1),
	PANEL_DIRECTIONS = {-1, 1},
	LEFT = -1,
	RIGHT = 1,
	BLOCK_IMAGES = {"middle_block_1", "middle_block_2", "middle_block_3", "middle_block_4"},
	REWARD_TYPES = {COIN = 1, SMALL_CHEST = 2, CHEST = 3},
	REWARD_STATES = {ACTIVE = 1, MISSED = 2},
	REWARD_TICKS = 5,
	REWARD_TICK_TIME = 0.2,
	SMALL_CHEST_ROW = 11,
	BORDER_IMAGES = {"border_1", "border_2"},
	BORDER_TYPES = {LEFT = 1, RIGHT = 2},
	GAMESTATE = {START = 1, PLAY = 2, WIN = 3, LOSE = 4, END = 5},
	POPUP_STATES = {SHOW = 1, HIDE = 2},
	POPUP_INTENTS = {START = "start", LOSE = "lose", WIN = "win"},
	POPUP_TITLE_START_POS = 120,
	POPUP_SUBTITLE_START_POS = -120,
	hero_factory = "/industry#hero_factory",
	skull_factory = "/industry#skull_factory",
	panel_factory = "/industry#panel_factory",
	block_factory = "/industry#block_factory",
	coin_factory = "/industry#coin_factory",
	small_chest_factory = "/industry#small_chest_factory",
	chest_factory = "/industry#chest_factory",
	border_factory = "/industry#border_factory",
	torches = "/torches#torches",
	hud = "/HUD#hud",
	popups = "/popups#popups",
	money_counter = "/money_counter",
	money_label = "/money_counter#money_label",
	money_icon_mask = "/money_counter#money_icon_mask",
	countdown_counter = "/countdown_counter",
	countdown_label = "/countdown_counter#countdown_label",
	countdown_icon_mask = "/countdown_counter#countdown_icon_mask",
	gameplay_manager = "/gameplay_manager#gameplay_manager",
	gamestate = 0,
	row = 0,
	column = 0,
	length = 0,
	speed = 0,
	time = 0,
	score = 0,
	panel_moving = false,
	hero = {},
	skull = {},
	panels = {},
	chest = nil,
	rewards = {}
}
return world