local BORDER_IMAGES = { "border_1", "border_2" }
local BORDER_TYPES = { LEFT = 1, RIGHT = 2 }

go.property("side", 0)

function init(self)
	self.random_border = BORDER_IMAGES[math.random(#BORDER_IMAGES)]
	msg.post("#sprite_right", hash("disable"))
	msg.post("#sprite", hash("play_animation"), {id = hash(self.random_border)})
	if self.side == BORDER_TYPES.LEFT then
		sprite.set_hflip("#sprite", true)
		msg.post("#sprite_right", hash("enable"))
		msg.post("#sprite_left", hash("disable"))
	end
end