--done

local w = require("modules.world")

go.property("side", 0)

function init(self)
	local random_border = w.BORDER_IMAGES[math.random(#w.BORDER_IMAGES)]
	msg.post("#sprite_right", "disable")
	msg.post("#sprite", "play_animation", {id = hash(random_border)})
	if self.side == w.BORDER_TYPES.LEFT then
		sprite.set_hflip("#sprite", true)
		msg.post("#sprite_right", "enable")
		msg.post("#sprite_left", "disable")
	end
end