local function panel_properties(message)
	local y = 24 + message.row * 16
	local x_l = 24
	local x_r = 136 - message.length * 16
	return {
		start_position = vmath.vector3(x_l, y, -4),
		end_position = vmath.vector3(x_r, y, -4),
		movement_speed = message.speed,
		length = message.length }
end

function on_message(self, message_id, message, sender)
	if message_id == hash("spawn") then
		local panel = factory.create("#panel_factory", nil, nil, panel_properties(message))
	end
end