local function panel_properties(message)
	return {
		start_position = vmath.vector3(24, 24 + message.row * 16, -4),
		end_position = vmath.vector3(136 - message.length * 16, 24 + message.row * 16, -4),
		movement_speed = message.speed,
		length = message.length }
end

function on_message(self, message_id, message, sender)
	if message_id == hash("spawn") then
		local panel = factory.create("#panel_factory", nil, nil, panel_properties(message))
	end
end