local w = require("modules.world")

go.property("amount", 0)

local function collect(self)
	if self.amount == w.REWARD_TYPES.CHEST then w.chest = nil end
	go.delete() --TODO: animate
	msg.post(w.gameplay_manager, "collected", {amount = self.amount})
end

function on_message(self, message_id, message, sender)
	if message_id == hash("trigger_response") then
		if message.enter == true then collect(self) end
	end
end